#!/usr/bin/env bash
#Write a Bash script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed (refer to the example)
#Requirements:
#You must use the for loop (while and until are forbidden)
#Do not display hidden files


for file in *
do
	# check if the file is a regular file and not hidden
	if [ -f "$file"  ] && [[ "$file" != .* ]]
	then

	# get the part of the filename after the first dash	
	
		name=$(echo "$file" | cut -d '-' -f 2-)

	# print the name in a list format
	echo "$name"
	fi
done
